### ISSUE TITLE
cant download

### ISSUE THREAD

**Issue by hafizaarif** [qawemlilo/nodetube#1]
actually i was trying to see your work but i failed to download any video..error was cannot set headers afters they are sent..

**Comment by qawemlilo** [comment]
Hi @hafizaarif, I have not updated this project in quite a while. Will test and update.

**Comment by hafizaarif** [comment]
sure, let me know

On Mon, Aug 15, 2016 at 7:50 PM, Qawelesizwe Mlilo <notifications@github.com

**Comment by qawemlilo** [comment]
@hafizaarif I have updated the project, please let me know if you continue to experience problems.

**Comment by hafizaarif** [comment]
Ok, let me check...

**Comment by qawemlilo** [comment]
Hi @hafizaarif, was this issue resolved?
